language: elixir

elixir:
  - 1.4.0
otp_release:
  - 18.3.4

env:
  - EVENT_STORE_VERSION='14.04-v3.9.0'

before_install:
  - wget http://download.geteventstore.com/binaries/EventStore-OSS-Ubuntu-${EVENT_STORE_VERSION}.tar.gz
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --mem-db 2>&1> eventstore.log &

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
